#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/.nfscripts.env"

SUPER_VISOR_RESTART_REQUIRED=false
DB_NAME="$1"

#parse params
while [[ $# -gt 0 ]]
do
key="$1"


case $key in
    -s|--supervisor)
    SUPER_VISOR_RESTART_REQUIRED=true
    shift # past argument
    ;;
esac
shift # past argument or value
done


if $SUPER_VISOR_RESTART_REQUIRED ; then
	service supervisor stop
fi

mysql -u "$DB_USER" --password="$DB_PASSWORD" -e "drop database $DB_NAME;"
echo -e "${GREEN_COLOR}Database dropped${NO_COLOR}"

if $SUPER_VISOR_RESTART_REQUIRED ; then
	service supervisor start
fi
