#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/.nfscripts.env"
source "$DIR/osdetector"


if [ "$OS" == "$OS_WINDOWS" ] ; then
    {
        start "C:\Windows\System32\drivers\etc\hosts"
    } || {
        echo -e "${RED_COLOR}Error${NO_COLOR}"
    }
else
    SUBL="$(which subl)"
    if [ -z ${SUBL+x} ]; then
        {
            nano /etc/hosts
        } || {
            echo -e "${RED_COLOR}Error${NO_COLOR}"
        }
    else
        {
            subl /etc/hosts
        } || {
            {
                nano /etc/hosts
            } || {
                echo -e "${RED_COLOR}Error${NO_COLOR}"
            }
        }
    fi
fi

