#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ENV_PATH="$DIR/../.nfscripts.env"


RED_COLOR='\033[0;31m'
GREEN_COLOR='\033[0;32m'
NO_COLOR='\033[0m'



DB_HOST="localhost"

echo "Enter your mysql user:"

read DB_USER

echo "Enter your mysql password:"

read DB_PASSWORD



echo -e "DB_HOST=\"$DB_HOST\"" > $ENV_PATH
echo -e "DB_USER=\"$DB_USER\"" >> $ENV_PATH
echo -e "DB_PASSWORD=\"$DB_PASSWORD\"" >> $ENV_PATH
echo "RED_COLOR=\"\033[0;31m\"" >> $ENV_PATH
echo "GREEN_COLOR=\"\033[0;32m\"" >> $ENV_PATH
echo "NO_COLOR=\"\033[0m\"" >> $ENV_PATH

echo -e "${GREEN_COLOR}Your information is updated${NO_COLOR}"
echo -e "${GREEN_COLOR}Try command \"nfupdate\" when you want to update them again${NO_COLOR}"
